[workspace]
resolver = "2"
members = ["apps/app", "packages/app-lib", "packages/launcher-core"]
exclude = ["packages/launcher-core/upstream/daedalus", "packages/launcher-core/upstream/path-util", "packages/launcher-core/upstream/modrinth-content-management"]
[workspace.package]
edition = "2024"
license = "GPL-3.0-only"
repository = "https://github.com/Yozekkk/ncreate-launcher"
[profile.release]
opt-level = "s"
strip = true
lto = "thin"
[profile.dev]
debug = 0
